.travis.yml
OptimizelySDK.DemoApp/OptimizelySDK.DemoApp.csproj
OptimizelySDK.Tests/BucketerTest.cs
OptimizelySDK.Tests/EventTests/DefaultEventDispatcherTest.cs
OptimizelySDK.Tests/EventTests/EventBuilderTest.cs
OptimizelySDK.Tests/EventTests/LogEventTest.cs
OptimizelySDK.Tests/OptimizelySDK.Tests.csproj
OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK.Tests/ProjectConfigTest.cs
OptimizelySDK.Tests/UtilsTests/ConditionEvaluatorTest.cs
OptimizelySDK.Tests/UtilsTests/PrivateObject.cs
OptimizelySDK.Tests/UtilsTests/ValidatorTest.cs
OptimizelySDK.Tests/packages.config
OptimizelySDK/OptimizelySDK.csproj

Summary of Changes.
- Replaced UnitTesting framework to NUnit (Compatible with Mono)
- Logic for changing .net framework changed.
- Removed Microsoft. Unittesting assembly (Not compatible with travis & Mono)
- A class created to access private memebers & fields using reflection. (Microsoft.UnitTesting assembly was being used before).
@mikeng13 @aliabbasrizvi

Travis Compatible build.

---

OptimizelySDK.Net35/packages.config
OptimizelySDK.Net40/OptimizelySDK.Net40.csproj
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/packages.config
OptimizelySDK.Package/pack.ps1
OptimizelySDK.sln

Newtonsoft for .netframework 4.0 had runtime 4.000 version while 3.5 had 2.000.
When OptimizelySDK dll for framework was being used, it was installing runtime 4.0 version while we were using 3.5 dll for framework 4.0 as well, so it was assuming 2.0 runtime version. I have separated out 4.0 & 3.5 using same code base but DLL is different now.
@mikeng13

runtime enviornment issue netframework 4.0 fixed

---

CHANGELOG.MD
OptimizelySDK.Package/OptimizelySDK.nuspec
OptimizelySDK.Tests/EventTests/EventBuilderTest.cs
OptimizelySDK/Event/Builder/EventBuilder.cs

Bump to 1.2.0 for release.

---

OptimizelySDK.Tests/EventTests/EventBuilderTest.cs
OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK/Event/Builder/EventBuilder.cs
OptimizelySDK/Optimizely.cs

In the Conversion Params, variation was calculated from the Bucket.Bucket, so whitelisted, forcedvariation was not being considered. I have changed the argument type to Map and Track method is getting from variation from DecisionService & passing it to the EventBuilder conversion params.

Bug fix: Track method was sending bucketer variation in every case

---

OptimizelySDK.Net35/OptimizelySDK.Net35.csproj
OptimizelySDK.Net40/OptimizelySDK.Net40.csproj
OptimizelySDK.NetStandard16/OptimizelySDK.NetStandard16.csproj
OptimizelySDK.Tests/OptimizelySDK.Tests.csproj
OptimizelySDK/OptimizelySDK.csproj
OptimizelySDK/Properties/AssemblyInfo.cs

This P.R. leaves task of calling sn.exe and strongnaming entirely in pack.ps1's hands.
There were some new issues with the redundant and not wholely effective calls to sn.exe
in VS 2017 custom "After Build" commands.  One issue is these cause "Build FAILED"s
in our E2E tests which rely on '/bin/sh -c dotnet build --configuration Release'
instead of msbuild.
The E2E regression goes away in this P.R.

snk now only mentioned by pack.ps1

---

OptimizelySDK.DemoApp/Controllers/DemoController.cs
OptimizelySDK.Tests/DecisionServiceTest.cs
OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK.Tests/TestData.cs
OptimizelySDK/Optimizely.cs

C# SDK should return variation object instead of variation key, 
- Test cases updated
- GetVariation & Activate method updated
- Demo Site updated.

GetVariation should return variation object.

---

OptimizelySDK.Net35/OptimizelySDK.Net35.csproj
OptimizelySDK.Net40/OptimizelySDK.Net40.csproj
OptimizelySDK.NetStandard16/OptimizelySDK.NetStandard16.csproj
OptimizelySDK.Tests/DecisionServiceTest.cs
OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK/Bucketing/DecisionService.cs
OptimizelySDK/Entity/FeatureDecision.cs
OptimizelySDK/Optimizely.cs
OptimizelySDK/OptimizelySDK.csproj

C# SDK should have same implementation as in PHP.
Return DecisionFeature object, instead of variation from getVariationForFeature.

getvariationforfeature should return DecisionFeature entity

---

OptimizelySDK.Tests/EventTests/EventBuilderTest.cs
OptimizelySDK.Tests/UtilsTests/EventTagUtilsTest.cs
OptimizelySDK/Utils/EventTagUtils.cs

e2e causing an issue, unable to send conversion event with revenue value. Please check if it works.

event tag should parse value from dictionary to int.

---

OptimizelySDK.Package/OptimizelySDK.nuspec

Optimizely SDK was unable to find the murmurhash.dll which was actually bundled with murmurhash-signed sdk but dependencies had only murmurhash, the main difference was the publickey token was assigned in the murmurhash-signed sdk. 
Repro Steps
Install OptimizelySDK from nuget package. Run the this code in any sample app.
var b = new OptimizelySDK.Bucketing.Bucketer(new DefaultLogger());
b.GenerateBucketValue("user1");
It will raise exception.

murmurhash fix.

---

CHANGELOG.md
OptimizelySDK.DemoApp/packages.config
OptimizelySDK.Package/OptimizelySDK.nuspec
OptimizelySDK.Package/verifysn.ps1
OptimizelySDK/Optimizely.cs

OASIS-2517 Release 2.0.0 GA
This pull request would like to merge the "2.0.0-beta1" branch onto the "2.0.x" branch.
As advertised in the CHANGELOG.md
(https://github.com/optimizely/csharp-sdk/blob/2.0.0-beta1/CHANGELOG.md):
This major release of the Optimizely SDK introduces APIs for Feature Management.
New Features
Introduces the IsFeatureEnabled API to determine whether to show a feature to a user or not.
```
var enabled = OptimizelyClient.IsFeatureEnabled("my_feature_key", "user_1", userAttributes);
```
You can also get all the enabled features for the user by calling the following method which returns a list of strings representing the feature keys:
```
var enabledFeatures = OptimizelyClient.GetEnabledFeatures("user_1", userAttributes);
```
Introduces Feature Variables to configure or …

OASIS-2517 Release 2.0.0 GA

---

OptimizelySDK.Net35/OptimizelySDK.Net35.csproj
OptimizelySDK.Net40/OptimizelySDK.Net40.csproj
OptimizelySDK.NetStandard16/OptimizelySDK.NetStandard16.csproj
OptimizelySDK/IOptimizely.cs
OptimizelySDK/Optimizely.cs
OptimizelySDK/OptimizelySDK.csproj

Fixes #92.
Extracted an interface for all public members.
Also fixed a couple of the xmldocs.

Adds IOptimizely interface

---

OptimizelySDK.Tests/BucketerTest.cs
OptimizelySDK/Bucketing/Bucketer.cs

We are checking whitelisted users in decision service, get variation method. This logic was placed when DecisionService class didn't exist.

Whitelisted bucketing logic is in DecisionService

---

CHANGELOG.md

This was merged in but the actual deploy process took longer and lasted until 4 days later.

chore: Change release date on v2.2.0 to actual date it was published.

---

CONTRIBUTING.md
pull_request_template.md

- Adds commit message guidelines in `CONTRIBUTING.md`
- Adds PR template for Github PRs

chore(contrib): Add PR template and commit message guidelines.

---

OptimizelySDK.Tests/ProjectConfigTest.cs
OptimizelySDK/ProjectConfig.cs

- Forced variation key passed as an empty String will be considered as invalid.
- Updated unit tests for empty string variation key.

fix(set-forced-variation): Treats empty variation key as invalid and does not reset variation.

---

OptimizelySDK.Tests/EventTests/EventBuilderTest.cs
OptimizelySDK/Utils/EventTagUtils.cs

0 and 1 after deserialization converted into long and we were not considering long in the numeric method. just added it. Along with I realized to add short/uint as well. 

fix(eventtagsutils) : don't exclude falsy values

---

.travis.yml
OptimizelySDK.Travis.sln

- Update OptimizelySDK.Travis.sln to produce Net40, Net35 builds
- Generate NetStandard16 builds as well (in separate stage)
- Upload dlls to s3
- OASIS-4100

ci(codesign): upload build artifacts to s3

---

.travis.yml

move unit tests into their own stage for clarity and allow us to
build with mono 5.2.0 only
- The "what"; a concise description of each logical change
- Another change

ci(travis): remove building mono 5.18.0

---

OptimizelySDK.NetStandard16/OptimizelySDK.NetStandard16.csproj
OptimizelySDK.NetStandard16/Properties/AssemblyInfo.cs

.csproj for NetStandard16 previously did not include AssemblyInfo.cs
which contains versioning information. Because of this, it used an
automatically generated one similar to the one described here:
https://github.com/dotnet/cli/issues/4783#issuecomment-382695175
We now provide the AssemblyInfo.cs to include during the build and
explicitly tell it not to autogenerate.
after building, check versioning like this:
```
ikdasm -assembly OptimizelySDK.NetStandard16/bin/Debug/netstandard1.6/OptimizelySDK.NetStandard16.dll
Assembly Table
Name:          OptimizelySDK.NetStandard16
Hash Algoritm: 0x00008004
Version:       3.0.0.0
Flags:         0x00000001
PublicKey:     BlobPtr (0x00000e4e)
...
```

fix(versioning): NetStandard16

---

OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK.Tests/ProjectConfigTest.cs
OptimizelySDK.Tests/TestData.json
OptimizelySDK/Optimizely.cs

- Feature variable APIs now return default variable value when featureEnabled property is false.
- Added unit tests.

feat(api): Feature variable APIs now return default variable value when featureEnabled property is false.

---

OptimizelySDK.Net35/OptimizelySDK.Net35.csproj
OptimizelySDK.Net40/OptimizelySDK.Net40.csproj
OptimizelySDK.NetStandard16/OptimizelySDK.NetStandard16.csproj
OptimizelySDK.Tests/NotificationTests/NotificationCenterTests.cs
OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK/Notifications/NotificationCenter.cs
OptimizelySDK/Optimizely.cs
OptimizelySDK/OptimizelySDK.csproj
OptimizelySDK/Utils/DecisionInfoTypes.cs

- Implemented Decision Notification Listener for activate and getVariation APIs.
- Added unit tests.

feat(api): Decision Notification Listener for activate and getVariation APIs.

---

OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK/Optimizely.cs

instead of enum value, we need actual descriptive value in variabletype

Feature variable fix.

---

OptimizelySDK.Tests/DecisionServiceTest.cs
OptimizelySDK.Tests/ProjectConfigTest.cs
OptimizelySDK/Bucketing/DecisionService.cs
OptimizelySDK/Config/DatafileProjectConfig.cs
OptimizelySDK/Optimizely.cs
OptimizelySDK/ProjectConfig.cs

Reverts optimizely/csharp-sdk#162

Revert "Move forced variations into DecisionService."

---

.travis.yml

by default, "dotnet build" generates dlls in "debug mode"
need to add "-c Release" to generate dll in "release mode"

ci(travis): netstandard16.dll release mode

---

OptimizelySDK.Tests/ConfigTest/HttpProjectConfigManagerTest.cs
OptimizelySDK/Config/HttpProjectConfigManager.cs
OptimizelySDK/Config/PollingProjectConfigManager.cs

Polling interval should be default when 0 or -ve value provided
Blocking timeout should be default when 0 or -ve value provided
Due call, should be made after releasing lock. 

fix(defaulttiming): issues fixed related to default timings

---

README.md

- The "what"; a concise description of each logical change
- Another change

readme: Updated Readme

---

CHANGELOG.md

- Addressed feedback mentioned in https://github.com/optimizely/csharp-sdk/pull/177
No test plan.

fix(release): Changelog correction

---

OptimizelySDK.Tests/EventTests/BatchEventProcessorTest.cs
OptimizelySDK.Tests/EventTests/EventFactoryTest.cs
OptimizelySDK/Event/BatchEventProcessor.cs
OptimizelySDK/Event/Entity/EventContext.cs
OptimizelySDK/Event/Entity/ImpressionEvent.cs

- When flush interval is 0, then it should use default otherwise it should use mentioned interval, same for timeout interval.
- Cleanup code.
- Testing with FSC, should pass all tests.
- No issue filed.

fix(EP): Event processor fixes

---

OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK/Config/HttpProjectConfigManager.cs
README.md

`HttpProjectConfigManager` should start polling immediately unless `WithDefaultStart` sets `false` in HttpProjectConfigManager.Builder class instance.
Need to check with FSC.

polling config manager should be started by default.

---

OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK/Optimizely.cs

- GetFeatureVariableDouble was returning 0 for FR culture. Fixed this issue by returning Invariant culture.
- Added unit test to set FR culture and asserted expected value. 
- Also added unit test for other feature variable APIs.
- FSC should pass all tests.

fix(locale): GetFeatureVariableDouble was not returning expected value for FR culture

---

.travis.yml
CHANGELOG.md
OptimizelySDK.DemoApp/README.md
OptimizelySDK.DemoApp/Scripts/README.md

- The "what"; a concise description of each logical change
- Another change

ci(travis): add mdspell

---

OptimizelySDK.Tests/EntityTests/FeatureVariableTest.cs
OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK.Tests/ProjectConfigTest.cs
OptimizelySDK.Tests/TestData.json
OptimizelySDK/Entity/FeatureVariable.cs
OptimizelySDK/Optimizely.cs

- FeatureVariableType enum removed.
- Using constant values for Type which are string
- `Type` variable  is now `string` type in `FeatureVariable`.
- Added unit tests which will make sure that additional types shouldn't have any breaking change.
- E2E should pass without modifying any code.
- FeatureVariableType and GetFeatureVariableType were public, users who are using these undocumented type may have issues if they upgrade SDK.

feature variable type enum removed

---

CHANGELOG.md

chore: prepare for release 3.4.1

---

OptimizelySDK.Tests/UtilsTests/ExperimentUtilsTest.cs
OptimizelySDK/AudienceConditions/AudienceIdCondition.cs

- Updating audience evaluation log level to be debug. The only info level log will be the one corresponding to the result of overall evaluation of an audience.

fix(log-level) Adjusting log level on audience evaluation logs

---

CHANGELOG.md
OptimizelySDK.Tests/ConfigTest/HttpProjectConfigManagerTest.cs
OptimizelySDK/Config/HttpProjectConfigManager.cs
OptimizelySDK/Config/PollingProjectConfigManager.cs
OptimizelySDK/OptimizelyFactory.cs

- Adds support for Authenticated Datafiles.
- Added a HttpClient wrapper for HttpProjectConfigManager.
Added new unit tests
FSC is passing here. 
https://travis-ci.com/github/optimizely/fullstack-sdk-compatibility-suite/builds/171678195

feat: Add Authenticated Datafile Support

---

OptimizelySDK.Net35/OptimizelySDK.Net35.csproj
OptimizelySDK.Net40/OptimizelySDK.Net40.csproj
OptimizelySDK.NetStandard16/OptimizelySDK.NetStandard16.csproj
OptimizelySDK.NetStandard20/OptimizelySDK.NetStandard20.csproj
OptimizelySDK.Tests/OptimizelyJSONTest.cs
OptimizelySDK.Tests/OptimizelySDK.Tests.csproj
OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK/Optimizely.cs
OptimizelySDK/OptimizelyJSON.cs
OptimizelySDK/OptimizelySDK.csproj

- Renamed all references of a class from OptimizelyJson to OptimizelyJSON.
- OptimizelyJSON in .netStandard20 was under entity, while in other projects it was at root. Fixed it.
- All unit tests and FSC tests must be passed.

fix: Renaming optimizely json to OptimizelyJSON

---

OptimizelySDK.Tests/ConfigTest/HttpProjectConfigManagerTest.cs
OptimizelySDK.Tests/ConfigTest/PollingProjectConfigManagerTest.cs
OptimizelySDK.Tests/OptimizelyTest.cs

- Called Dispose method on every HttpConfigManager instance after test, Problem was Continuous polling of older instances were called for new mocked instance which is why test cases were being failed.
- Added maximum wait time to avoid deadlock or stale situation, OnReady wait until gets resolved, if no valid Config is provided, it remains unresolved which causes deadlock.
- All unit test must pass.

added disposed and max wait time.

---

OptimizelySDK.Tests/App.config
OptimizelySDK.Tests/ClientConfigHandlerTest.cs
OptimizelySDK.Tests/OptimizelyFactoryTest.cs
OptimizelySDK/ClientConfigHandler.cs
OptimizelySDK/OptimizelyFactory.cs
README.md

- Added datafileAccessToken in ClientConfigHandler to read it from App.config.
Added unit tests

Feat: Added DatafileAccessToken in ClientConfigHandler to read from App.config

---

OptimizelySDK.Tests/AudienceConditionsTests/ConditionEvaluationTest.cs
OptimizelySDK.Tests/DecisionServiceTest.cs
OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK.Tests/UtilsTests/ExperimentUtilsTest.cs
OptimizelySDK.Tests/UtilsTests/ValidatorTest.cs
OptimizelySDK/AudienceConditions/BaseCondition.cs
OptimizelySDK/Bucketing/DecisionService.cs
OptimizelySDK/Optimizely.cs
OptimizelySDK/Utils/ExperimentUtils.cs

- Added and updated missing audience evaluation logs.
added unit tests must pass and all FSC scenarios should pass

fix(logs): Added and refactored audience and feature variable evaluation logs

---

.travis.yml

- Source clear should be first n stage
- Added dotnet, otherwise source clear was unable to run it's job.
Checked here, and it's working fine. 
https://travis-ci.org/github/optimizely/csharp-sdk/jobs/712722775

fix: srcclr should be first in a job

---

OptimizelySDK/OptimizelyFactory.cs

- DatafileAccessToken is only allowed to 4.0 above, OptimizelyFactory is for all versions, added a condition to set accesstoken only for 4.0 above.
- Unit test must pass 
- FSC must pass.
- Manually checked, build is compiling succesfully.

fix: Datafile accesstoken is not accessible to .net 3.5 and 4.0

---

OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK.Tests/ProjectConfigTest.cs
OptimizelySDK/Config/DatafileProjectConfig.cs
OptimizelySDK/OptlyConfig/OptimizelyConfig.cs
OptimizelySDK/OptlyConfig/OptimizelyConfigService.cs
OptimizelySDK/ProjectConfig.cs

Summary
-------
- Add datafile accessor methods/functionalities
Testing
-------
- All unit tests and FSC must pass
https://travis-ci.com/github/optimizely/fullstack-sdk-compatibility-suite/jobs/377668178

feat: Add datafile accessor

---

OptimizelySDK.Tests/AudienceConditionsTests/ConditionEvaluationTest.cs
OptimizelySDK/AudienceConditions/SemanticVersion.cs

- Multiple fixed for sem-versioning
- Compare build version and pre-release fix
- Multiple `-` is now handled.
All FSC tests must pass
Added unit tests

fix: Semantic version fix and multiple dash signs check added

---

OptimizelySDK.Tests/OptimizelyFactoryTest.cs
OptimizelySDK.Tests/OptimizelySDK.Tests.csproj
OptimizelySDK.Tests/Utils/TestData.cs
OptimizelySDK.Tests/emptydatafile.json
OptimizelySDK/OptimizelyFactory.cs

- NewDefaultInstance shouldn't cause optimizely instance to raise exception while handling error, by default all DefaultErrorHandler shouldn't raise exception.
- Passed logger in default error handler and made raise exception to false.
- Added unit test. 
- FSC with empty datafile scenario must pass.
https://travis-ci.com/github/optimizely/fullstack-sdk-compatibility-suite/builds/182487252

fix: error handler not raise exception while using optimizelyfactory

---

OptimizelySDK.Net35/OptimizelySDK.Net35.csproj
OptimizelySDK.Net40/OptimizelySDK.Net40.csproj
OptimizelySDK.NetStandard16/OptimizelySDK.NetStandard16.csproj
OptimizelySDK.NetStandard20/OptimizelySDK.NetStandard20.csproj
OptimizelySDK.Tests/EventTests/EventEntitiesTest.cs
OptimizelySDK.Tests/EventTests/EventFactoryTest.cs
OptimizelySDK.Tests/EventTests/UserEventFactoryTest.cs
OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK.Tests/ProjectConfigTest.cs
OptimizelySDK.Tests/TestData.json
OptimizelySDK/Config/DatafileProjectConfig.cs
OptimizelySDK/Event/Builder/EventBuilder.cs
OptimizelySDK/Event/Builder/Params.cs
OptimizelySDK/Event/Entity/Decision.cs
OptimizelySDK/Event/Entity/DecisionMetadata.cs
OptimizelySDK/Event/Entity/ImpressionEvent.cs
OptimizelySDK/Event/EventFactory.cs
OptimizelySDK/Event/UserEventFactory.cs
OptimizelySDK/Optimizely.cs
OptimizelySDK/OptimizelySDK.csproj
OptimizelySDK/ProjectConfig.cs

* Add experiment/feature flag key, variation key and type to impression events.
* Send events for **ALL** decision types.
* Add `Metadata` field to EventBatch.Decisions to capture flag type, key and variation key.
* All FSC and unit tests should pass

feat(flag-decisions): Add support for sending flag decisions along with decision metadata. 

---

CHANGELOG.md
OptimizelySDK.DemoApp/Properties/AssemblyInfo.cs
OptimizelySDK.Net35/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard16/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard20/Properties/AssemblyInfo.cs
OptimizelySDK.Tests/Properties/AssemblyInfo.cs
OptimizelySDK/Properties/AssemblyInfo.cs

- updated change log date
- updated assembly version.

chore 3.7: change logs and version update 

---

OptimizelySDK.Tests/EventTests/EventFactoryTest.cs
OptimizelySDK/Event/Entity/DecisionMetadata.cs
OptimizelySDK/Event/UserEventFactory.cs
OptimizelySDK/Optimizely.cs

- While sending impression events, metadata should have enabled field as well.
- updated unit tests
- FSC should pass
- Custom Trigger  - https://travis-ci.com/github/optimizely/fullstack-sdk-compatibility-suite/builds/199495582

feat: added enabled field in metadata.

---

OptimizelySDK.Tests/BucketerTest.cs
OptimizelySDK.Tests/DecisionServiceTest.cs
OptimizelySDK.Tests/UtilsTests/ExperimentUtilsTest.cs

- Added few unit tests to test that DecisionReasons contains the info logs upon setting decideOption as INCLUDE_REASONS
It should pass with FSC and all unit tests should pass

Feat: Added unit tests for reasons addInfo logs 

---

OptimizelySDK.Tests/OptimizelyUserContextTest.cs
OptimizelySDK/OptimizelyUserContext.cs

Clone the current user-context and pass it to optimizely.decide(), decide all and in decideForKeys
- user context can be changed while processing the decide request.
- with this fix, decide can return the copy of the original user-context as a part of the decision

feat(decide): clone user-context before calling optimizely decide

---

OptimizelySDK.Tests/OptimizelyUserContextTest.cs
OptimizelySDK/Optimizely.cs

- SendImpressionEvent will return false when event is not sent and return true when sent successfully
- In case of userEvent is null it will return false

Fix: SendImpressionEvent will return false when event is not sent

---

OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK/Config/PollingProjectConfigManager.cs

- Added unit tests to verify when source type is rollout and SendFlagDecisions is false then event should not dispatch and decisionEventDispatched should be false.
- Added unit tests to verify when source type is rollout and SendFlagDecisions is true then event should dispatch and decisionEventDispatched should be true.

Feat: Added unit test to verify in which SendFlagDecision is true and false

---

OptimizelySDK.Tests/ConfigTest/HttpProjectConfigManagerTest.cs
OptimizelySDK/Config/HttpProjectConfigManager.cs

- When no ErrorHandler is provided in the HttpProjectConfigManager, it provides DefaultErrorHandler that raise exception without providing any argument. 
- Fixed by explicitly setting throwException=false in the constructor.
- Added a unit test.
- All FSC should be passed.

fix: DefaultErrorHandler shouldn't raise exception

---

OptimizelySDK.Package/OptimizelySDK.nuspec

- System.Configuration.ConfigurationManager dependency was missing in nuget package.
- licenseUrl is deprecated, updated to license element.
- IconUrl is deprecated, updated to Icon
- All unit tests must pass
- Manual testing, generated nuget package and tested 
- FSC must pass.

fix: nuget added configuration manager dependency for .netstandard 2.0

---

OptimizelySDK.Tests/OptimizelyFactoryTest.cs
OptimizelySDK/OptimizelyFactory.cs

- Polling interval and blocking timeout period of configManager can be now set using optimizelyFactory and the provided intervals will be given priority over config file values. 
All Unit tests and FSC tests should pass.
- [OASIS-7690](https://optimizely.atlassian.net/browse/OASIS-7690)

Feat: Added set polling interval and set blocking timeout period method in OptimizelyFactory

---

OptimizelySDK.Tests/OptimizelyConfigTests/OptimizelyConfigTest.cs
OptimizelySDK.Tests/ProjectConfigTest.cs
OptimizelySDK.Tests/TestData.json
OptimizelySDK.Tests/emptydatafile.json
OptimizelySDK.Tests/typed_audience_datafile.json
OptimizelySDK/Config/DatafileProjectConfig.cs
OptimizelySDK/OptlyConfig/OptimizelyConfig.cs
OptimizelySDK/OptlyConfig/OptimizelyConfigService.cs
OptimizelySDK/ProjectConfig.cs

- Sdk key and environment keys are going to be parse in sdk and will be sent back in optimizelyConfig
All unit tests and FSC tests should pass

Feat: added SDKkey and environment key in project config

---

OptimizelySDK/Bucketing/Bucketer.cs
OptimizelySDK/Config/DatafileProjectConfig.cs
OptimizelySDK/ProjectConfig.cs

- Fixed an issue related to duplicate experimentKey.
- While trying to get variation from the variationkeyMap, it was unable to find because the latest experimentKey was overriding the previous one.
- Run with FSC 
https://app.travis-ci.com/github/optimizely/fullstack-sdk-compatibility-suite/builds/232246224

feat: Duplicate experiment key issue with multi feature flag

---

CHANGELOG.md
OptimizelySDK.DemoApp/Properties/AssemblyInfo.cs
OptimizelySDK.Net35/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard16/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard20/Properties/AssemblyInfo.cs
OptimizelySDK.Tests/Properties/AssemblyInfo.cs
OptimizelySDK/Properties/AssemblyInfo.cs

prepare for release 3.9.1
All FSC and unit tests must be passed.

chore: preparing 3.9.1 release

---

OptimizelySDK.Tests/OptimizelyConfigTests/OptimizelyConfigTest.cs
OptimizelySDK/OptlyConfig/OptimizelyConfigService.cs

- Typed audiences should be taken priority, if any audienceId is same in audiences and typedAudiences, typedAudiences should be considered.
- Updated unit test and FSC should be passed with new testcases.

fix: typed audiences should take priority.

---

OptimizelySDK/OptlyConfig/OptimizelyConfig.cs
OptimizelySDK/OptlyConfig/OptimizelyFeature.cs

- Added depreciation warning on Optimizelyconfig.ExperimentsMap field as this was missed in previous PRs.

Added depreciation warning on Optimizelyconfig.ExperimentsMap field

---

OptimizelySDK.Tests/OptimizelySDK.Tests.csproj
OptimizelySDK.Tests/TestSetup.cs
OptimizelySDK/OptimizelyUserContext.cs

The following versions of Optimizely C# SDK would use the methods defined on the class _OptimizelyUserContext_ to perform some processes, E.G: Decide, TrackEvent, DecideAll, etc...
Then, it is required on the vast majority of unit testing frameworks, for mocking this object to be able to override such members.
This can be accomplished, at least on C#, usually in two ways:
1. Declaring an _interface_ (with the methods to be overriden) and having the class implementing it.
2. Declaring the members as _virtual_, would allow also allow the testing framework to override them.
This PR uses the second approach, it makes the methods on _OptimizelyUserContext_ virtual.
Also fixes a problem with development environments with a culture different from English.

Create virtual methods on user context

---

CHANGELOG.md
OptimizelySDK.DemoApp/Properties/AssemblyInfo.cs
OptimizelySDK.Net35/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard16/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard20/Properties/AssemblyInfo.cs
OptimizelySDK.Tests/Properties/AssemblyInfo.cs
OptimizelySDK/Properties/AssemblyInfo.cs

chore: preparing 3.10.0 release.

---

OptimizelySDK.Net35/OptimizelySDK.Net35.csproj
OptimizelySDK.Net40/OptimizelySDK.Net40.csproj
OptimizelySDK.NetStandard16/OptimizelySDK.NetStandard16.csproj
OptimizelySDK.NetStandard20/OptimizelySDK.NetStandard20.csproj
OptimizelySDK.Tests/DecisionServiceTest.cs
OptimizelySDK.Tests/ForcedDecisionsStoreTest.cs
OptimizelySDK.Tests/OptimizelySDK.Tests.csproj
OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK.Tests/OptimizelyUserContextTest.cs
OptimizelySDK.Tests/ProjectConfigTest.cs
OptimizelySDK/Bucketing/DecisionService.cs
OptimizelySDK/Config/DatafileProjectConfig.cs
OptimizelySDK/Entity/Result.cs
OptimizelySDK/Event/Builder/EventBuilder.cs
OptimizelySDK/Event/EventFactory.cs
OptimizelySDK/Event/UserEventFactory.cs
OptimizelySDK/ForcedDecisionsStore.cs
OptimizelySDK/Optimizely.cs
OptimizelySDK/OptimizelyDecisionContext.cs
OptimizelySDK/OptimizelySDK.csproj
OptimizelySDK/OptimizelyUserContext.cs
OptimizelySDK/ProjectConfig.cs

- Refactored code and fixed some minor issues. 
- Introduced ForcedDecisionStore class that will be used for storing forced decisions.
- Removed DecisionKey, instead introduced map of map in forceddecisionstore class. 
- GetFlagVariationKey removed from optimizely method, single source of truth for all mappings is DatafileProjectConfig class
- Added config in the FindValidatedForcedDecision since no access of ProjectConfig directly from OptimizelyUserContext.
- Refactored DecisionService, not needed for GetVariationFromExperimentRules or GetVariationFromDeliveryRules etc ... 
- No need of Separate mapping method in DatafileProjectConfig, tried to use existing maps to prepare FlagVariationsMap.
- Documentation corrected.
All FSC and unit tests should pass
- I still see a little room of …

Refact: Refactored Forced decision

---

OptimizelySDK.DemoApp/OptimizelySDK.DemoApp.csproj
OptimizelySDK.DemoApp/packages.config

- Update Log4Net to latest possible version to resolve [CVE-2018-1285](https://github.com/advisories/GHSA-2cwj-8chv-9pp9)
- all tests and fsc still pass
- Demo App loads after update.

fix: CVE-2018-1285 update Log4Net

---

CHANGELOG.md
OptimizelySDK.DemoApp/Properties/AssemblyInfo.cs
OptimizelySDK.Net35/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard16/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard20/Properties/AssemblyInfo.cs
OptimizelySDK.Tests/Properties/AssemblyInfo.cs
OptimizelySDK/Properties/AssemblyInfo.cs

chore: prepare for release 3.11.0

---

.editorconfig
.gitignore
OptimizelySDK.sln.DotSettings

- Begin implementing [style guide](https://github.com/optimizely/style-guides/tree/main/csharp) guidance in Microsoft Visual Studio and JetBrains Rider
- As source code is added and maintained, we want to slowly apply the Optimizely style guide/coding practice.
- ⚠️ Avoid instances where a code change is lost among formatting changes. (@msohailhussain let's talk on this point)
- Confirm .editorconfig and .sln.DotSettings are applied to other devs' IDE. 
- Confirm no changes to source code files unless explicit call to refactor/code formatter in IDE.
- Confirm no functional side effects or breakage after applying code formatting.
- OASIS-8305

Add IDE-level linting of code style guide

---

OptimizelySDK.Tests/EmptyRolloutRule.json
OptimizelySDK.Tests/ProjectConfigTest.cs
OptimizelySDK.sln.DotSettings
OptimizelySDK/Config/DatafileProjectConfig.cs

- Handle possible empty string `rolloutId` in datafile
An empty string rolloutId should be ignored and not raise and exception
Unit test added to OptimizelySDK.Tests/ProjectConfigTest.cs
- OASIS-8370

[OASIS-8370] Handle null, empty, or whitespaces for RolloutId

---

.editorconfig
.github/workflows/csharp.yml
.github/workflows/ticket_reference_check.yml
OptimizelySDK.Tests/App.config

- Fix failing lint_code_base
- Change to use Windows image to compile SDK
- Verify all GitHub Actions are passing
- FSSDK-8681

chore: Fix and Reconfigure GitHub Actions

---

OptimizelySDK.Tests/OdpTests/OdpConfigTest.cs
OptimizelySDK.Tests/OdpTests/OdpEventManagerTests.cs
OptimizelySDK.Tests/OdpTests/OdpManagerTest.cs
OptimizelySDK.Tests/OptimizelySDK.Tests.csproj
OptimizelySDK/Odp/IOdpEventManager.cs
OptimizelySDK/Odp/IOdpManager.cs
OptimizelySDK/Odp/IOdpSegmentManager.cs
OptimizelySDK/Odp/OdpConfig.cs
OptimizelySDK/Odp/OdpEventManager.cs
OptimizelySDK/Odp/OdpManager.cs
OptimizelySDK/Odp/OdpSegmentManager.cs
OptimizelySDK/OptimizelySDK.csproj

Added ODPManager Implementation which does the following.
1. Initializes and provides access to ODPEventManager and ODPSegmentManager
2. Provides updated ODPConfig settings to event manager and segment manager.
3. Stops Event Manager thread when closed.
1. Manually tested thoroughly
2. Added unit tests.
FSSDK-8453

feat: Added ODPManager implementation

---

OptimizelySDK.Tests/OdpTests/OdpEventManagerTests.cs
OptimizelySDK/Notifications/NotificationCenterRegistry.cs
OptimizelySDK/Odp/OdpEventManager.cs

- Refactored OdpEventManager flushEvent function. 
- To wait for events using flushInterval when eventBatch is not empty.
- Or wait indefinitely if no event is in batch until any event arrive. 
- Avoid calling flush on shutdown if no events are present 
- Avoid calling unnecessary flushQueue if _currentBatch.Count is zero. 
Passing build link with FSC: [link](https://github.com/optimizely/fullstack-sdk-compatibility-suite/actions/runs/4163960853/jobs/7206348700)
- [TODO]

Fix: ODP Event manager not consistent in triggering events.

---

CHANGELOG.md

- As noted in https://github.com/optimizely/csharp-sdk/issues/328, we missed documenting some released updates.
Tests should continue to succeed.
- FSSDK-8955

[FSSDK-8955] Update CHANGELOG

---

OptimizelySDK.Package/OptimizelySDK.nuspec

- Updated version from 3.2.0 to 3.11.2.
- Updated release notes link to https://github.com/optimizely/csharp-sdk/blob/3.11.2/CHANGELOG.md.
- Updated copyright year from 2019 to 2023.
- Added README.md file to package.
- All unit tests should pass
- FSSDK-9006

[FSSDK-9006] Corrections to nuspec

---

OptimizelySDK.Tests/OdpTests/OdpEventManagerTests.cs
OptimizelySDK/Odp/Constants.cs
OptimizelySDK/Odp/Entity/OdpEvent.cs
OptimizelySDK/Odp/IOdpManager.cs
OptimizelySDK/Odp/OdpEventManager.cs
OptimizelySDK/Odp/OdpManager.cs
OptimizelySDK/Optimizely.cs

- Check if ODP events have at least one key-value pair for identifiers.
If not, discard the request without sending to the ODP server.
- Add a test with empty identifiers and null identifier.
- All tests should pass. 
- [FSSDK-8948](https://jira.sso.episerver.net/browse/FSSDK-8948)

[FSSDK-8948] fix(odp): check odp identifiers not null or empty before sending

---

OptimizelySDK.Tests/OdpTests/OdpEventManagerTests.cs
OptimizelySDK.Tests/OdpTests/OdpSegmentApiManagerTest.cs
OptimizelySDK.Tests/OdpTests/OdpSegmentManagerTest.cs
OptimizelySDK/Odp/Constants.cs
OptimizelySDK/Odp/Enums.cs
OptimizelySDK/Odp/IOdpSegmentApiManager.cs
OptimizelySDK/Odp/OdpEventApiManager.cs
OptimizelySDK/Odp/OdpEventManager.cs
OptimizelySDK/Odp/OdpSegmentApiManager.cs
OptimizelySDK/Odp/OdpSegmentManager.cs

As a bug bash engineer, I would like ODP events being sent from the C# SDK to not return an HTTP Status 400.
- Existing unit and integration test should pass
- Bug bash engineer's test app should pass end-to-end testing
- FSSDK-9039

[FSSDK-9039] Fix e2e ODP event response

---

OptimizelySDK.Tests/OdpTests/OdpEventManagerTests.cs
OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK/IOptimizely.cs
OptimizelySDK/Odp/Constants.cs
OptimizelySDK/Odp/Entity/OdpEvent.cs
OptimizelySDK/Odp/OdpEventManager.cs
OptimizelySDK/Optimizely.cs
OptimizelySDK/Utils/CollectionExtensions.cs

- Validate SendOdpEvent empty action and type parameters
- Generate new idempotence_id for every OdpEvent
added tests to:
- OdpEventManagerTests.cs
- OptimizelyTest.cs
[FSSDK-9079](https://jira.sso.episerver.net/browse/FSSDK-9079)

[FSSDK-9079] fix: send odp event empty values

---

OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK/Optimizely.cs

- Add check for ProjectConfig in odp methods.
This will ensure the datafile has been fetched first.
all tests pass
[FSSDK-9055](https://jira.sso.episerver.net/browse/FSSDK-9055)

[FSSDK-9055] fix: add config check in odp methods

---

.editorconfig
.github/workflows/csharp.yml
OptimizelySDK.Tests/ConfigTest/PollingProjectConfigManagerTest.cs
OptimizelySDK.Tests/NotificationTests/NotificationCenterTests.cs
OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK/Optimizely.cs

- Fix OdpManager not having a default instantiation in `Optimizely` client
`OptimizelyFactory` provides a default which is desirable.  The `Optimizely` constructors should follow this.
- Add covering and passing unit test for `Optimizely`
- FSC integration tests should continue to pass
- FSSDK-9090

[FSSDK-9090] Default instantiation of OdpManager for Optimizely constructors

---

OptimizelySDK.Tests/OdpTests/OdpSegmentApiManagerTest.cs
OptimizelySDK/Odp/Entity/Extension.cs
OptimizelySDK/Odp/OdpSegmentApiManager.cs

Support a new format for ODP `InvalidIdentifierException` (when SDK fetches segments with a non-registered userId).
```
"extensions": {
"code": "INVALID_IDENTIFIER_EXCEPTION",
"classification": "DataFetchingException"
}
```
- Added unit tests to cover the new response format.
- Existing unit tests should pass
- FSC should continue to pass
- FSSDK-9128

[FSSDK-9128] fix: Handle ODP INVALID_IDENTIFIER_EXCEPTION code

---

OptimizelySDK/Config/PollingProjectConfigManager.cs

- Send config update notification before unblocking so odp config is updated.
all tests pass
[FSSDK-9055](https://jira.sso.episerver.net/browse/FSSDK-9055)

[FSSDK-9055] fix: send config update notification before unblocking

---

OptimizelySDK.Tests/ConfigTest/HttpProjectConfigManagerTest.cs
OptimizelySDK/Config/HttpProjectConfigManager.cs

- Last-Modified was not following the RFC 1123 spec for date and time formatting
- Relates to #360 
- Updated existing unit tests to look for correct formatting
- All other existing tests should continue to pass.
- FSSDK-9538

[FSSDK-9538] bug: Fix last modified formatting

---

.github/workflows/csharp.yml
.github/workflows/integration_test.yml
CHANGELOG.md
OptimizelySDK.DemoApp/Properties/AssemblyInfo.cs
OptimizelySDK.Net35/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard16/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard20/Properties/AssemblyInfo.cs
OptimizelySDK.Tests/ConfigTest/HttpProjectConfigManagerTest.cs
OptimizelySDK.Tests/Properties/AssemblyInfo.cs
OptimizelySDK/Config/HttpProjectConfigManager.cs
OptimizelySDK/Properties/AssemblyInfo.cs

- Cherry-picked from main branch bug fix
- Updated versions numbers including missed one
- Add changelog update
- All unit tests and e2e non-AAT tests should pass
- ODP e2e tests will be temporarily turned off 
- FSSDK-9538

[FSSDK-9538] chore Cherry-pick & prep for 3.11.4 release

---

.github/ISSUE_TEMPLATE/BUG-REPORT.yml
.github/ISSUE_TEMPLATE/ENHANCEMENT.yml
.github/ISSUE_TEMPLATE/FEATURE-REQUEST.md
.github/ISSUE_TEMPLATE/config.yml

- Add GitHub issues templates
- Review via https://github.com/mikechu-optimizely/csharp-sdk/issues/new/choose
- No C# code changed.  Existing unit and e2e tests are expected to pass.
- FSSDK-9551

[FSSDK-9551] Add GitHub Issue templates

---

OptimizelySDK.Tests/ConfigTest/PollingProjectConfigManagerTest.cs
OptimizelySDK/Config/PollingProjectConfigManager.cs

-  Implements a warning log for polling interval less than 30s
- [FSSDK-9526](https://jira.sso.episerver.net/browse/FSSDK-9526)

[FSSDK-9526] refact: Implements a warning log for polling interval less than 30s

---

OptimizelySDK.Tests/OptimizelyConfigTests/OptimizelyConfigTest.cs
OptimizelySDK/OptlyConfig/OptimizelyConfigService.cs

When duplicate experiment key found in the data file, SDK returns correct experiment map in OptimizelyConfig
- Keep the latest experiment key, found in the datafile experiment list
- Add warning log "Duplicate keys found in datafile: {key-name}"
- Updated existing test for duplicate key
- All other tests cases are expected to pass
- [FSSDK-9783](https://jira.sso.episerver.net/browse/FSSDK-9783)

[FSSDK-9783] Return Latest Experiment When Duplicate Keys in Config

---

CHANGELOG.md
LICENSE
OptimizelySDK.DemoApp/Properties/AssemblyInfo.cs
OptimizelySDK.Net35/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard16/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard20/Properties/AssemblyInfo.cs
OptimizelySDK.Tests/Properties/AssemblyInfo.cs
OptimizelySDK/Properties/AssemblyInfo.cs
README.md

- Incremement version numbers removing the beta tag
- Update changelog, readme.md, & license
- All unit and e2e test suites should pass
- [FSSDK-8581](https://jira.sso.episerver.net/browse/FSSDK-8581)

[FSSDK-8581] chore: Prepare for 4.0.0 release

---

.github/workflows/csharp.yml
.github/workflows/csharp_release.yml
.github/workflows/integration_test.yml

Instead of directly using variables that can contain user input, new intermediate variables were introduced so that script injection attacks could be mitigated. Also removed unnecessary use of ${{ }} as using it makes the file vulnerable.
- [FSSDK-10665](https://jira.sso.episerver.net/browse/FSSDK-10665)

[FSSDK-10665] fix: Github Actions YAML files vulnerable to script injections corrected

---

.github/workflows/sonarqube.yml

Updating sonarqube versions
[- "THING-1234" or "Fixes #123"](https://jira.sso.episerver.net/browse/EC3-1687)  FSSDK-1111

EC3-1687 Update sonarqube.yml [FSSDK-1111]

---

.github/workflows/csharp.yml
.github/workflows/integration_test.yml
OptimizelySDK.DemoApp/Scripts/README.md
README.md

Clean up travis references (not used any more).
No new tests.
- "FSSDK-11077"

[FSSDK-11077] clean up travis

---

OptimizelySDK.Tests/OptimizelyUserContextTest.cs
OptimizelySDK/Optimizely.cs

This pull request adds a new validation for null flag keys in the decision logic, ensuring that passing a null flag key to the `Decide` method returns a proper error decision. It also introduces a corresponding unit test to verify this behavior.
**Error handling improvements:**
* Added a check in `Optimizely.cs` to return an error decision if the flag key passed to `Decide` is null, using a specific error message (`FLAG_KEY_INVALID`).
**Testing enhancements:**
* Added a new test, `DecideNullFlagKey`, in `OptimizelyUserContextTest.cs` to verify that passing a null flag key returns the expected error decision.
[FSSDK-11837](https://jira.sso.episerver.net/browse/FSSDK-11837)

[FSSDK-11837] legacy api adjustment with key null support in decide

---

OptimizelySDK.NetStandard20/OptimizelySDK.NetStandard20.csproj
OptimizelySDK.Tests/CmabTests/DefaultCmabClientTest.cs
OptimizelySDK.Tests/OptimizelySDK.Tests.csproj
OptimizelySDK/Cmab/CmabConstants.cs
OptimizelySDK/Cmab/CmabModels.cs
OptimizelySDK/Cmab/CmabRetryConfig.cs
OptimizelySDK/Cmab/DefaultCmabClient.cs
OptimizelySDK/Cmab/ICmabClient.cs
OptimizelySDK/Exceptions/OptimizelyException.cs
OptimizelySDK/OptimizelySDK.csproj

* Added `ICmabClient` interface defining the contract for fetching decisions from the CMAB prediction service.
* Implemented `DefaultCmabClient` class, which interacts with the CMAB service using `HttpClient`, handles request/response, supports retries, and validates responses.
* Introduced supporting classes: `CmabModels` for request/response structure, `CmabConstants` for endpoint and error messages, and `CmabRetryConfig` for exponential backoff configuration.
* Added new exception classes: `CmabException`, `CmabFetchException`, and `CmabInvalidResponseException` to represent various CMAB client error states.
* Added `DefaultCmabClientTest` unit tests covering success, error, invalid response, and retry scenarios for the CMAB client.
* Updated project files to include new CMAB client, …

[FSSDK-11150] cmab client implementation
