CHANGELOG.MD

Add changelog.

---

OptimizelySDK.Tests/EventTests/EventBuilderTest.cs
OptimizelySDK.Tests/TestData.json
OptimizelySDK/Event/Builder/EventBuilder.cs
OptimizelySDK/Event/Builder/Params.cs
OptimizelySDK/ProjectConfig.cs

Added anonymize_ip attribute in commonparams
Updated test cases to include "anonymize_ip" in the JSON data.

Feature - Anonymize IP 

---

.travis.yml
OptimizelySDK.Net35/OptimizelySDK.Net35.csproj
OptimizelySDK.Net40/OptimizelySDK.Net40.csproj
OptimizelySDK.NetStandard16/OptimizelySDK.NetStandard16.csproj
OptimizelySDK.Tests/ProjectConfigTest.cs
OptimizelySDK.Tests/TestData.json
OptimizelySDK/Entity/FeatureFlag.cs
OptimizelySDK/Entity/FeatureVariable.cs
OptimizelySDK/Entity/FeatureVariableUsage.cs
OptimizelySDK/Entity/Rollout.cs
OptimizelySDK/Entity/Variation.cs
OptimizelySDK/Exceptions/OptimizelyException.cs
OptimizelySDK/OptimizelySDK.csproj
OptimizelySDK/ProjectConfig.cs

Datafile parsing & Validation
Travis Issue fixed (set mono specific version for unit testing)

Feature Flag & Roll out models

---

OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK/Optimizely.cs

isFeatureEnabled must return only boolean value. NULL is replaced with false. 
@mikeng13

isfeatureenabled should return boolean value.

---

OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK.Tests/UtilsTests/PrivateObject.cs
OptimizelySDK/Optimizely.cs

Changed Optimizely class property notificationcenter to public modifier. 
And now using NotificationCenter of Optimizely object in OptimizelyTest

Optimizely has private property NotificationCenter

---

CHANGELOG.md
README.md

Synch "master" CHANGELOG.md and README.md to
1.3.x CHANGELOG.md and README.md (latest release 1.3.0).

Update CHANGELOG.md and README.md to 1.3.0

---

OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK.Tests/UtilsTests/EventTagUtilsTest.cs
OptimizelySDK/Event/Builder/EventBuilder.cs
OptimizelySDK/Optimizely.cs
OptimizelySDK/Utils/EventTagUtils.cs

Added test cases for eventtagutils proper logging.

EventTagUtils proper Logging

---

CHANGELOG.md
OptimizelySDK.DemoApp/packages.config
OptimizelySDK.Package/OptimizelySDK.nuspec
OptimizelySDK.Package/verifysn.ps1
OptimizelySDK/Optimizely.cs

This pull request updates master branch with the 2.0.0 version number bump
and latest 2.0.0 CHANGELOG.md

OASIS-2517 Duplicate 2.0.0 release changes and CHANGELOG.md onto master

---

CHANGELOG.md
OptimizelySDK.DemoApp/Properties/AssemblyInfo.cs
OptimizelySDK.Net35/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.Package/OptimizelySDK.nuspec
OptimizelySDK.Package/verifysn.ps1
OptimizelySDK.Tests/Properties/AssemblyInfo.cs
OptimizelySDK/Properties/AssemblyInfo.cs

Need to re-publish package as it was signed incorrectly. This bumps the version and adds a changelog entry for it.

chore: Prepare 2.2.1 release.

---

OptimizelySDK.Tests/EventTests/EventBuilderTest.cs
OptimizelySDK/Utils/Validator.cs

Summary
-------
Don't track NaN, infinity doubles or numeric values greater than 2^53 in EventBuilder.

feat(event_builder): Don't track NaN, infinity and value greater than 2^53.

---

CHANGELOG.md
OptimizelySDK.DemoApp/Properties/AssemblyInfo.cs
OptimizelySDK.Net35/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.Package/OptimizelySDK.nuspec
OptimizelySDK.Package/verifysn.ps1
OptimizelySDK.Tests/EventTests/EventBuilderTest.cs
OptimizelySDK.Tests/Properties/AssemblyInfo.cs
OptimizelySDK/Properties/AssemblyInfo.cs
OptimizelySDK/Utils/EventTagUtils.cs

- Merges in the bug fix for #132 
- Bumps version numbers

 chore: Prepare 2.2.2 release

---

CHANGELOG.md
OptimizelySDK.DemoApp/Properties/AssemblyInfo.cs
OptimizelySDK.Net35/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.Package/verifysn.ps1
OptimizelySDK.Tests/Properties/AssemblyInfo.cs
OptimizelySDK/Properties/AssemblyInfo.cs

remaining versioning changes to complete https://optimizely.atlassian.net/browse/OASIS-4088

chore(update version)

---

.travis.yml

Enable SourceClear scans in Travis CI.
OASIS-4079

ci(security): Enable SourceClear

---

OptimizelySDK.Tests/DecisionServiceTest.cs
OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK.Tests/ProjectConfigTest.cs
OptimizelySDK/Bucketing/DecisionService.cs
OptimizelySDK/Entity/FeatureDecision.cs
OptimizelySDK/Optimizely.cs
OptimizelySDK/ProjectConfig.cs
OptimizelySDK/Utils/DecisionInfoTypes.cs

- Incorporated new decision notification listener changes.
- Added unit tests.

feat(decision-listener): Incorporated new decision notification listener changes.

---

CHANGELOG.md

chore: update changelog for 3.1.1 release

---

OptimizelySDK.Net35/OptimizelySDK.Net35.csproj
OptimizelySDK.Net40/OptimizelySDK.Net40.csproj
OptimizelySDK.NetStandard16/OptimizelySDK.NetStandard16.csproj
OptimizelySDK.Tests/EventTests/EventEntitiesTest.cs
OptimizelySDK.Tests/OptimizelySDK.Tests.csproj
OptimizelySDK/Event/Entity/ConversionEvent.cs
OptimizelySDK/Event/Entity/Decision.cs
OptimizelySDK/Event/Entity/EventBatch.cs
OptimizelySDK/Event/Entity/EventContext.cs
OptimizelySDK/Event/Entity/ImpressionEvent.cs
OptimizelySDK/Event/Entity/Snapshot.cs
OptimizelySDK/Event/Entity/SnapshotEvent.cs
OptimizelySDK/Event/Entity/UserEvent.cs
OptimizelySDK/Event/Entity/Visitor.cs
OptimizelySDK/Event/Entity/VisitorAttribute.cs
OptimizelySDK/OptimizelySDK.csproj

- Data models to represent Impression/Conversion event on client/server side
- Unit test to verify after serialization datamodel is converted into expected server payload
- Conversion Event (Already there)
- Impression Event (In Progress)

feat(epmodel): Event Processor datamodel

---

CHANGELOG.md
OptimizelySDK.DemoApp/Properties/AssemblyInfo.cs
OptimizelySDK.DemoApp/packages.config
OptimizelySDK.Net35/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard16/Properties/AssemblyInfo.cs
OptimizelySDK.Package/OptimizelySDK.nuspec
OptimizelySDK.Tests/Properties/AssemblyInfo.cs
OptimizelySDK/Properties/AssemblyInfo.cs

- Bump versions in the required files
- Added ChangeLog for 3.2.0 version

 chore: update changelog for 3.2.0 release

---

CHANGELOG.md
OptimizelySDK.DemoApp/Properties/AssemblyInfo.cs
OptimizelySDK.DemoApp/packages.config
OptimizelySDK.Net35/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard16/Properties/AssemblyInfo.cs
OptimizelySDK.Package/OptimizelySDK.nuspec
OptimizelySDK.Tests/ConfigTest/HttpProjectConfigManagerTest.cs
OptimizelySDK.Tests/Properties/AssemblyInfo.cs
OptimizelySDK/Config/HttpProjectConfigManager.cs
OptimizelySDK/Config/PollingProjectConfigManager.cs
OptimizelySDK/Properties/AssemblyInfo.cs
README.md

3.2.x release

---

OptimizelySDK.DemoApp/Controllers/DemoController.cs

DemoApp has class called Config which was conflicting with SDK Config namespace.

fix(config-conflict): Class Config conflicts with namespace

---

OptimizelySDK.Tests/ConfigTest/HttpProjectConfigManagerTest.cs
OptimizelySDK/Config/HttpProjectConfigManager.cs

Changed log msgs to debug.
added more log msgs
Added unit tests

debug: Added log msgs for not providing values.

---

OptimizelySDK.Net40/OptimizelySDK.Net40.csproj
OptimizelySDK/Config/HttpProjectConfigManager.cs

Net40 constant was not defined to pull datafile. Added now.

fix(net40): Defined constant for net40

---

CHANGELOG.md
OptimizelySDK.DemoApp/Controllers/DemoController.cs
OptimizelySDK.Net40/OptimizelySDK.Net40.csproj
OptimizelySDK.Tests/ConfigTest/HttpProjectConfigManagerTest.cs
OptimizelySDK/Config/HttpProjectConfigManager.cs

- Resolved Config conflicts in demo app
- log msgs more precised
- defined constant in .net4.0 project file
- change log correction.

chore: 3.2.x cherry pick for release

---

.travis.yml

makes it possible to release from more than just "master" branch

ci(travis): release specific branch

---

.travis.yml

SDK_BRANCH should be passed to FSC using script.

fix(ci): SDK_BRANCH should be passed to FSC

---

.travis.yml
OptimizelySDK.NetStandard20/OptimizelySDK.NetStandard20.csproj
OptimizelySDK.NetStandard20/Properties/AssemblyInfo.cs
OptimizelySDK.Package/OptimizelySDK.nuspec
OptimizelySDK.Package/pack.ps1
OptimizelySDK.sln

- Adding .netstandard 2.0 support
Need to test with FSC
https://travis-ci.com/optimizely/fullstack-sdk-compatibility-suite/jobs/221353384

ci(.net20): Adding net standard 2.0 support

---

OptimizelySDK.Tests/EventTests/BatchEventProcessorTest.cs
OptimizelySDK.Tests/UtilsTests/PrivateObject.cs
OptimizelySDK/Event/BatchEventProcessor.cs
OptimizelySDK/OptimizelyFactory.cs

1- Batch Event Dispatcher default to a DefaultEventDispatcher if not provided
2- Allow a logger to be set on the factory for customizing the logger
Added test in BatchEventProcessorTest.cs 
[OASIS-5256]

Default Event Dispatcher In case of null

---

OptimizelySDK.Tests/ConfigTest/HttpProjectConfigManagerTest.cs
OptimizelySDK/Config/HttpProjectConfigManager.cs

When not providing any value, it was just logging not setting up periodinterval and blocking timeout value.
Added unit tests.

fix(blockingtimeout): Blocking timeout was not being assigned

---

.travis.yml
CHANGELOG.md

chore: prepare 3.4.0 release

---

OptimizelySDK.Tests/ConfigTest/HttpProjectConfigManagerTest.cs
OptimizelySDK/Config/HttpProjectConfigManager.cs

- Added gzip support for downloading datafile.
- Unit test doesn't seem possible.
- Will add FSC for it.
https://travis-ci.com/github/optimizely/fullstack-sdk-compatibility-suite/builds/168800505

feat(gzip): Adding gzip support for framework 4.5 or above.

---

OptimizelySDK.Tests/ConfigTest/HttpProjectConfigManagerTest.cs
OptimizelySDK.Tests/Utils/TestHttpProjectConfigManagerUtil.cs
OptimizelySDK/Config/HttpProjectConfigManager.cs

- Improved logs while polling data or exception is raised.
- Added unit test and verified logging.
- No impact on integration test. Must pass.

fix: improved logging

---

CHANGELOG.md
OptimizelySDK.DemoApp/Properties/AssemblyInfo.cs
OptimizelySDK.Net35/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard16/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard20/Properties/AssemblyInfo.cs
OptimizelySDK.Tests/ConfigTest/HttpProjectConfigManagerTest.cs
OptimizelySDK.Tests/ConfigTest/PollingProjectConfigManagerTest.cs
OptimizelySDK.Tests/OptimizelyTest.cs
OptimizelySDK.Tests/Properties/AssemblyInfo.cs
OptimizelySDK/Properties/AssemblyInfo.cs

chore: prepare for release 3.5.0

---

CHANGELOG.md

- update for release off of master of 3.6 includes semver and datafile accessors.
- added datafileAuthToken support in app.config
- Audience evaluation logs revised.
- fixed following issues
- no rollout rule, should not crash
- Set raiseException to false for ErrorHandler set in OptimizelyFactory 
- All unit tests and FSC must pass.

chore: 3.6 release 

---

CHANGELOG.md
OptimizelySDK.DemoApp/Properties/AssemblyInfo.cs
OptimizelySDK.Net35/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard16/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard20/Properties/AssemblyInfo.cs
OptimizelySDK.Tests/Properties/AssemblyInfo.cs
OptimizelySDK/Properties/AssemblyInfo.cs

- updated change log date
- updated assembly version.

chore 3.6: change logs and version update

---

CHANGELOG.md
OptimizelySDK.DemoApp/Properties/AssemblyInfo.cs
OptimizelySDK.Net35/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard16/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard20/Properties/AssemblyInfo.cs
OptimizelySDK.Tests/Properties/AssemblyInfo.cs
OptimizelySDK/Properties/AssemblyInfo.cs

- updated change log date
- updated assembly version.

chore 3.7.1: change logs and version update

---

CHANGELOG.md
OptimizelySDK.DemoApp/Properties/AssemblyInfo.cs
OptimizelySDK.Net35/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard16/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard20/Properties/AssemblyInfo.cs
OptimizelySDK.Tests/Properties/AssemblyInfo.cs
OptimizelySDK/Properties/AssemblyInfo.cs

chore: prepare for release 3.8.0

---

CHANGELOG.md
OptimizelySDK.DemoApp/Properties/AssemblyInfo.cs
OptimizelySDK.Net35/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard16/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard20/Properties/AssemblyInfo.cs
OptimizelySDK.Tests/Properties/AssemblyInfo.cs
OptimizelySDK/Properties/AssemblyInfo.cs

chore: preparing 3.9.0 release

---

.travis.yml
CHANGELOG.md
OptimizelySDK.DemoApp/Properties/AssemblyInfo.cs
OptimizelySDK.Net35/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard16/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard20/Properties/AssemblyInfo.cs
OptimizelySDK.Tests/Properties/AssemblyInfo.cs
OptimizelySDK/Bucketing/Bucketer.cs
OptimizelySDK/Config/DatafileProjectConfig.cs
OptimizelySDK/ProjectConfig.cs
OptimizelySDK/Properties/AssemblyInfo.cs

- Fix for duplicate experiment
- Change logs and project version updated.
All FSC must be passed.

Preparing v3.9.1

---

.travis.yml

- Trying with xenial for NetStandard1.6 and NetStandard2.0

fix: change it to xenial

---

OptimizelySDK.Tests/DecisionServiceTest.cs
OptimizelySDK.Tests/OptimizelyUserContextTest.cs
OptimizelySDK/OptimizelyUserContext.cs

- Remove config-ready check from forced-decision apis
- Unit and FSC tests

fix(ForcedDecision): remove config-ready check from forced-decision apis

---

OptimizelySDK.Tests/DecisionServiceTest.cs
OptimizelySDK.Tests/OptimizelyUserContextTest.cs
OptimizelySDK/Bucketing/DecisionService.cs
OptimizelySDK/Optimizely.cs
OptimizelySDK/OptimizelyUserContext.cs

-  Moves findValidatedForcedDecision method to decision service as validatedForcedDecision
All unit test and FSC tests should pass.

move validate forced decision to decision service

---

.github/workflows/csharp.yml
.github/workflows/integration_test.yml

- Git actions updated to run FSC on git actions.
- Need to change travisci-tools branch from `mnoman/gitActions` to `master`

feat: updated for fsc git action

---

CHANGELOG.md
OptimizelySDK.DemoApp/Properties/AssemblyInfo.cs
OptimizelySDK.Net35/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard16/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard20/Properties/AssemblyInfo.cs
OptimizelySDK.Tests/Properties/AssemblyInfo.cs
OptimizelySDK/Properties/AssemblyInfo.cs

- Prepare for release 3.11.1
- OASIS-8370
- OASIS-8371

chore: prepare for release 3.11.1

---

OptimizelySDK/Optimizely.cs

- Fix for incorrect documentation on Optimizely.IsFeatureEnabled
- Existing unit and FSC test should pass
- FSSDK-9999 just kidding it's for DOC-2699 but had to satisfy the check 😉

bug: return method doc for IsFeatureEnabled

---

.github/workflows/csharp.yml

- Trying to fix the DLL artifact uploads to AWS 
chatGPT for the win (hopefully)
Tests should pass
- FSSDK-8955

[FSSDK-8955] chore: Fix upload to S3 naming

---

CHANGELOG.md
OptimizelySDK.DemoApp/Properties/AssemblyInfo.cs
OptimizelySDK.Net35/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard16/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard20/Properties/AssemblyInfo.cs
OptimizelySDK.Tests/Properties/AssemblyInfo.cs
OptimizelySDK/Properties/AssemblyInfo.cs

- Corrections to nuspec generated during signing and upload.
The nuspec generated during code signing was incorrect.
- All tests should continue to pass
- Code signing process should succeed and publish
- FSSDK-9006

[FSSDK-9006] Semantic version bump 3.11.2.1

---

CHANGELOG.md
OptimizelySDK.DemoApp/OptimizelySDK.DemoApp.csproj
OptimizelySDK.DemoApp/Properties/AssemblyInfo.cs
OptimizelySDK.Net35/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard16/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard20/Properties/AssemblyInfo.cs
OptimizelySDK.Tests/Properties/AssemblyInfo.cs
OptimizelySDK/Properties/AssemblyInfo.cs

- Update changelog 
- Bump version for Advanced Audience Targeting (AAT) beta 
All existing unit and FSC tests should pass. 
[FSSDK-9108](https://jira.sso.episerver.net/browse/FSSDK-9108)

[FSSDK-9108] Prep for 4.0.0-beta release 

---

OptimizelySDK/IOptimizely.cs

- Added missing methods in IOptimizely interface: GetFeatureVariableJSON(), GetOptimizelyConfig() and  GetAllFeatureVariables()
All tests should pass.
- [FSSDK-8701](https://jira.sso.episerver.net/browse/FSSDK-8701)

[FSSDK-8701]: Added missing methods in Optimizely interface

---

CHANGELOG.md
OptimizelySDK.DemoApp/Properties/AssemblyInfo.cs
OptimizelySDK.Net35/Properties/AssemblyInfo.cs
OptimizelySDK.Net40/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard16/Properties/AssemblyInfo.cs
OptimizelySDK.NetStandard20/Properties/AssemblyInfo.cs
OptimizelySDK.Tests/Properties/AssemblyInfo.cs
OptimizelySDK/Properties/AssemblyInfo.cs
README.md

- Minor bump semver
- Update docs
- Unit tests should pass
- I expect that e2e tests might still be problematic mentioned in #374 
- [FSSDK-10848](https://jira.sso.episerver.net/browse/FSSDK-10848)

[FSSDK-10848] Prepare release 4.1.0

---

.github/workflows/csharp_release.yml

- Bump the versions of the workflow step tools
- Add workflow_dispatch
- No code changes just `chore`
- "FSSDK-10848"

[FSSDK-10848] Update Actions tool versions & add workflow dispatch

---

.github/workflows/csharp.yml

Restore workflow to master branch
- FSSDK-11077

[FSSDK-11077] restore master workflow (cleanup)
